//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperVillains.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperVillains.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received ${0} for your service in arresting suspect(s)..
        /// </summary>
        internal static string CALLOUT_SV_BONUS_ARREST_SALARY {
            get {
                return ResourceManager.GetString("CALLOUT_SV_BONUS_ARREST_SALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received ${0} for your service in arresting or killing suspects..
        /// </summary>
        internal static string CALLOUT_SV_BONUS_SALARY {
            get {
                return ResourceManager.GetString("CALLOUT_SV_BONUS_SALARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have reports of gang-related violence by The Lost OMG in {0}, available units please respond..
        /// </summary>
        internal static string CALLOUT_SV_JOHNNY_MESSAGE {
            get {
                return ResourceManager.GetString("CALLOUT_SV_JOHNNY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIB is requesting assistance for peace disturbance of a civilian in {0}..
        /// </summary>
        internal static string CALLOUT_SV_LUIS_MESSAGE {
            get {
                return ResourceManager.GetString("CALLOUT_SV_LUIS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIB is requesting assistance for suspects fleeing the crime scene at {0}..
        /// </summary>
        internal static string CALLOUT_SV_LUIS_TBOGT_MSG {
            get {
                return ResourceManager.GetString("CALLOUT_SV_LUIS_TBOGT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilians report possible terrorist activity at {0}..
        /// </summary>
        internal static string CALLOUT_SV_NIKO_CIVIL_MSG {
            get {
                return ResourceManager.GetString("CALLOUT_SV_NIKO_CIVIL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have suspects in contact with officers on duty at {0}, backup is required..
        /// </summary>
        internal static string CALLOUT_SV_NIKO_MESSAGE {
            get {
                return ResourceManager.GetString("CALLOUT_SV_NIKO_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be advised, we are dealing with a dangerous biker leader: {0}, born {1} in Alderney. Advise all approaching units to be on the alert..
        /// </summary>
        internal static string TEXT_INFO_RELAY_SV_JOHNNY {
            get {
                return ResourceManager.GetString("TEXT_INFO_RELAY_SV_JOHNNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task update, officer. Several NGD members are on site and being attacked by The Lost OMG members. They require immediate assistance, pronto!.
        /// </summary>
        internal static string TEXT_INFO_RELAY_SV_JOHNNY_MISSION_UPDATE {
            get {
                return ResourceManager.GetString("TEXT_INFO_RELAY_SV_JOHNNY_MISSION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller is said that suspects are attempting to leave the scene. We are dispatching a unit close to your position now..
        /// </summary>
        internal static string TEXT_INFO_RELAY_SV_JOHNNY_PRANK {
            get {
                return ResourceManager.GetString("TEXT_INFO_RELAY_SV_JOHNNY_PRANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be advised, we have relayed information about suspect. Suspect is identified as {0}, born {1} in Northwood, Algonquin. Three others are unknown at this time and are considered armed and dangerous. Proceed with extreme prejudice..
        /// </summary>
        internal static string TEXT_INFO_RELAY_SV_LUIS {
            get {
                return ResourceManager.GetString("TEXT_INFO_RELAY_SV_LUIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is officer {0}, we are in contact with suspects! Suspect is carrying a rocket launcher! Requesting backup!.
        /// </summary>
        internal static string TEXT_INFO_RELAY_SV_NIKO {
            get {
                return ResourceManager.GetString("TEXT_INFO_RELAY_SV_NIKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer {0} is in contact with {1} with a rocket launcher! Taking him down!.
        /// </summary>
        internal static string TEXT_INFO_RELAY_SV_NIKO_SWAT {
            get {
                return ResourceManager.GetString("TEXT_INFO_RELAY_SV_NIKO_SWAT", resourceCulture);
            }
        }
    }
}
